version: '3'
services:
  llm-engine:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=sk-proj-JZm15xUo65pLTIFrX0lOT3BlbkFJ5AaO3MI3OF3c1C6sdJtM
      - REDIS_URL=redis://redis:6379
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
