version: '3'
services:
  myapp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=sk-proj-JZm15xUo65pLTIFrX0lOT3BlbkFJ5AaO3MI3OF3c1C6sdJtM
    depends_on:
      - redis
  redis:
    image: redis
